name: Build & push docker images

on:
  push:
    branches:
      - main
      - master
      - staging
      - test
      - ci
      - develop

    tags:
      - v*
      - release/v*

env:
  IMAGE_NAME: devcontainer-dind

jobs:
  build_and_push:
    name: Build and push
    if: "!contains(github.event.head_commit.message, 'Automated update') && !contains(github.event.head_commit.message, 'CI ignore')"
    # if: github.event_name == 'push'

    strategy:
      matrix:
        target: ["dotnet"]
        variant: ["debian"]
      fail-fast: true

    runs-on: ubuntu-latest

    # permissions:
    #   contents: read
    #   packages: write

    steps:
      # - name: Free more space
      #   id: free_space
      #   run: |
      #     set -e
      #     # Ensure enough space is available for build
      #     sudo apt-get autoremove -y
      #     sudo apt-get clean -y
      #     sudo rm -rf /usr/share/dotnet

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: DockerHub meta
        id: meta_docker
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME}}
          flavor: prefix=${{ matrix.target }}-
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=${{ matrix.target }}-
            type=edge

      - name: Github Container Registry meta
        id: meta_ghcr
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME}}
          flavor: prefix=${{ matrix.target }}-
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=${{ matrix.target }}-
            type=edge

      # - name: Get tag name
      #   id: get_tag_name
      #   run: |
      #     # Strip git ref prefix from version
      #     VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      #     # Strip "v" prefix from tag name
      #     [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
      #     # Use Docker `latest` tag convention
      #     [ "$VERSION" == "main" ] && VERSION=latest
      #     echo "::set-output name=tag::$(echo "$VERSION")"
      #     # Or
      #     echo "::set-output name=tag::$(echo "${{ github.ref }}" | grep -oP 'refs/tags/\K(.+)')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: containers/${{ matrix.target }}/.devcontainer
          file: containers/${{ matrix.target }}/.devcontainer/${{ matrix.variant }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta_docker.outputs.tags }}
            ${{ steps.meta_ghcr.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
